// ============================================================
// SKYTRUST INC — STATIC DATA FILES
// ============================================================

// --- Blog Posts ---
export const blogPosts = [
  {
    slug: 'zero-trust-architecture-guide',
    title: 'Zero Trust Architecture: A Complete Implementation Guide for 2025',
    excerpt: 'Zero Trust is no longer optional. Learn how to implement a robust ZTA that eliminates implicit trust across your entire network perimeter.',
    category: 'Best Practices',
    author: 'Marcus Chen',
    authorTitle: 'Chief Security Architect',
    readTime: '12 min read',
    date: '2025-07-15',
    tags: ['Zero Trust', 'Architecture', 'Network Security'],
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'ransomware-defense-playbook',
    title: 'The 2025 Ransomware Defense Playbook: Before, During, and After',
    excerpt: 'Ransomware attacks surged 87% in 2024. This definitive guide covers prevention, detection, containment, and recovery strategies that work.',
    category: 'Threat Intel',
    author: 'Sarah Mitchell',
    authorTitle: 'Head of Threat Intelligence',
    readTime: '15 min read',
    date: '2025-07-08',
    tags: ['Ransomware', 'Incident Response', 'Threat Intel'],
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'soc2-type2-checklist',
    title: 'SOC 2 Type II Readiness: The 47-Point Checklist Your Auditor Expects',
    excerpt: 'Preparing for your SOC 2 Type II audit? Our practitioners have distilled the exact controls and evidence you need to pass with confidence.',
    category: 'Compliance',
    author: 'Priya Nair',
    authorTitle: 'Compliance Director',
    readTime: '10 min read',
    date: '2025-06-28',
    tags: ['SOC 2', 'Compliance', 'Audit'],
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'cloud-misconfiguration-risks',
    title: 'The $4.9M Cloud Misconfiguration: How One AWS Setting Cost Everything',
    excerpt: 'A single misconfigured S3 bucket exposed 2.1M customer records. Walk through the forensic analysis and the 12 misconfigurations that lurk in most cloud environments.',
    category: 'Threat Intel',
    author: 'James Okafor',
    authorTitle: 'Cloud Security Lead',
    readTime: '8 min read',
    date: '2025-06-18',
    tags: ['Cloud Security', 'AWS', 'Misconfiguration'],
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'phishing-simulation-results',
    title: 'We Ran 50,000 Phishing Simulations. Here\'s What We Learned.',
    excerpt: 'After running phishing simulations across 500+ organizations, these are the 6 subject lines that fooled even security-aware employees.',
    category: 'Best Practices',
    author: 'Emily Torres',
    authorTitle: 'Security Awareness Lead',
    readTime: '7 min read',
    date: '2025-06-05',
    tags: ['Phishing', 'Social Engineering', 'Training'],
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'hipaa-2025-changes',
    title: 'HIPAA 2025 Amendments: What Healthcare Organizations Must Do Now',
    excerpt: 'The FY2025 HIPAA Security Rule amendments introduce significant new requirements. Our compliance team breaks down exactly what\'s changing and your action plan.',
    category: 'Compliance',
    author: 'Dr. Angela Reeves',
    authorTitle: 'Healthcare Compliance Specialist',
    readTime: '11 min read',
    date: '2025-05-22',
    tags: ['HIPAA', 'Healthcare', 'Compliance'],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
  },
];

// --- Case Studies ---
export const caseStudies = [
  {
    slug: 'regional-bank-pci-compliance',
    industry: 'Finance',
    title: 'Regional Bank Achieves PCI-DSS Compliance in 90 Days',
    challenge: 'A mid-size regional bank with 45 branches failed its PCI-DSS audit due to inadequate network segmentation, unencrypted card data at rest, and insufficient access controls.',
    solution: 'SkyTrust deployed a phased compliance program: network re-architecture with micro-segmentation, HSM-based encryption for cardholder data, and a full IAM overhaul with PAM tooling.',
    result: 'Passed PCI-DSS audit on first re-attempt. Reduced the cardholder data environment surface area by 70%. Zero security incidents in 18 months post-remediation.',
    metrics: [
      { label: 'Audit pass rate', value: '100%', desc: 'on first re-attempt' },
      { label: 'CDE reduction', value: '70%', desc: 'smaller attack surface' },
      { label: 'Incidents post-fix', value: '0', desc: 'in 18 months' },
    ],
    services: ['Compliance Consulting', 'Network Security'],
  },
  {
    slug: 'healthcare-system-breach-response',
    industry: 'Healthcare',
    title: 'Healthcare System Contained Active Breach in Under 4 Hours',
    challenge: 'A 12-hospital system detected suspicious lateral movement across their clinical network during peak hours. Ransomware was staging on 3 servers. Patient records at risk.',
    solution: 'SkyTrust Incident Response team was engaged via breach hotline. Activated isolation playbooks, performed live forensics, and coordinated with hospital IT to contain the threat while maintaining critical patient systems.',
    result: 'Threat fully contained in 3h 42min. No patient data exfiltrated. Ransomware eradicated before encryption phase. Full operations restored in 18 hours.',
    metrics: [
      { label: 'Containment time', value: '3h 42m', desc: 'vs 14h industry avg' },
      { label: 'Records protected', value: '2.4M', desc: 'patient records safe' },
      { label: 'Recovery time', value: '18hrs', desc: 'to full operations' },
    ],
    services: ['Incident Response', 'Threat Monitoring'],
  },
  {
    slug: 'saas-startup-soc2',
    industry: 'Technology',
    title: 'SaaS Startup Unlocks $12M Enterprise Deals with SOC 2 Type II',
    challenge: 'A 60-person SaaS company was losing enterprise deals because they lacked SOC 2 Type II certification. No dedicated security team, limited documentation, ad-hoc controls.',
    solution: 'SkyTrust implemented a 6-month readiness program: policy documentation library, technical controls implementation (encryption, logging, access reviews), and continuous monitoring.',
    result: 'Achieved SOC 2 Type II in 6 months. Closed 3 enterprise contracts worth $12M within 60 days of certification. Audit findings: zero exceptions.',
    metrics: [
      { label: 'Time to SOC 2', value: '6 mo.', desc: 'from zero to certified' },
      { label: 'Revenue unlocked', value: '$12M', desc: 'in new enterprise deals' },
      { label: 'Audit exceptions', value: '0', desc: 'clean certification' },
    ],
    services: ['Compliance Consulting'],
  },
];

// --- Glossary Terms ---
export const glossaryTerms = [
  { letter: 'A', term: 'Advanced Persistent Threat (APT)', definition: 'A prolonged, targeted cyberattack in which an intruder gains access to a network and remains undetected for an extended period. APTs are typically sponsored by nation-states or well-funded criminal organizations.' },
  { letter: 'A', term: 'Attack Surface', definition: 'The sum of all possible entry points (attack vectors) where an unauthorized user can attempt to enter data or extract data from an environment.' },
  { letter: 'B', term: 'Botnet', definition: 'A network of private computers infected with malicious software and controlled as a group without the owners\' knowledge, often used for DDoS attacks, spam campaigns, or cryptocurrency mining.' },
  { letter: 'C', term: 'CVE (Common Vulnerabilities and Exposures)', definition: 'A publicly disclosed list of cybersecurity vulnerabilities. Each CVE has a unique identifier and severity score (CVSS) to help organizations prioritize patching.' },
  { letter: 'D', term: 'DDoS (Distributed Denial of Service)', definition: 'An attack that attempts to disrupt normal traffic to a targeted server, service, or network by overwhelming the target with a flood of internet traffic from multiple sources.' },
  { letter: 'E', term: 'Endpoint Detection and Response (EDR)', definition: 'Security technology that continuously monitors endpoints (computers, mobile devices) to detect, investigate, and respond to threats in real time.' },
  { letter: 'F', term: 'Firewall', definition: 'A network security device that monitors and controls incoming and outgoing network traffic based on predetermined security rules, establishing a barrier between trusted and untrusted networks.' },
  { letter: 'I', term: 'IDS/IPS', definition: 'Intrusion Detection System (IDS) monitors network traffic for suspicious activity and issues alerts. Intrusion Prevention System (IPS) also actively blocks detected threats.' },
  { letter: 'M', term: 'MFA (Multi-Factor Authentication)', definition: 'An authentication method requiring two or more verification factors, such as something you know (password), have (device), or are (biometric), to gain access to a resource.' },
  { letter: 'M', term: 'MTTR (Mean Time to Respond)', definition: 'The average time it takes for a security team to respond to and remediate a security incident after it is detected. Lower MTTR indicates a more effective security operation.' },
  { letter: 'P', term: 'Penetration Testing', definition: 'An authorized, simulated cyberattack on a computer system to evaluate its security posture, identify vulnerabilities, and test the effectiveness of existing controls.' },
  { letter: 'P', term: 'Phishing', definition: 'A social engineering attack where attackers send fraudulent messages, typically email, designed to trick recipients into revealing sensitive information or installing malware.' },
  { letter: 'R', term: 'Ransomware', definition: 'Malicious software that encrypts a victim\'s files and demands payment (ransom) for the decryption key. Modern ransomware often also exfiltrates data for double extortion.' },
  { letter: 'S', term: 'SIEM (Security Information and Event Management)', definition: 'A solution that provides real-time analysis of security alerts generated by applications and network hardware. SIEM aggregates and correlates log data to identify anomalies.' },
  { letter: 'S', term: 'SOC (Security Operations Center)', definition: 'A centralized unit that monitors, detects, investigates, and responds to cybersecurity incidents on a 24/7 basis using people, processes, and technology.' },
  { letter: 'T', term: 'Threat Intelligence', definition: 'Evidence-based knowledge about existing or emerging threats, including context, mechanisms, indicators, implications, and actionable advice, used to inform decisions about the subject\'s response.' },
  { letter: 'V', term: 'Vulnerability', definition: 'A weakness in a system, application, or network that can be exploited by a threat actor to gain unauthorized access or cause harm. Vulnerabilities are rated by CVSS severity scores.' },
  { letter: 'Z', term: 'Zero Trust', definition: 'A security model that assumes no user or system is trustworthy by default, even within the corporate network. Every access request must be verified, authenticated, and authorized before being granted.' },
  { letter: 'Z', term: 'Zero-Day', definition: 'A software vulnerability that is unknown to the vendor and has no available patch. Zero-day exploits are particularly dangerous because defenders have no advance warning.' },
];

// --- Team Members ---
export const teamMembers = [
  {
    name: 'Alexandra Pierce',
    title: 'Chief Executive Officer',
    bio: 'Former Director of Engineering at a Fortune 100 firm with 20+ years in enterprise software and systems. Founded SkyTrust to build scalable, secure software and infrastructure accessible to organizations of all sizes.',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    linkedin: '#',
  },
  {
    name: 'Marcus Chen',
    title: 'Chief Security Architect',
    bio: 'CISSP, CISM certified. Previously led security architecture for a major cloud provider. Architect of SkyTrust\'s Zero Trust framework deployed across 200+ client environments.',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    linkedin: '#',
  },
  {
    name: 'Priya Nair',
    title: 'Director of Compliance',
    bio: 'Led audit programs at Big 4 accounting firm for 12 years. Expert in SOC 2, ISO 27001, HIPAA, and PCI-DSS. Has guided 150+ organizations through successful compliance certifications.',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    linkedin: '#',
  },
  {
    name: 'James Okafor',
    title: 'Head of Cloud Security',
    bio: 'AWS and GCP certified security specialist. Former senior engineer at a major cloud-native security startup. Specializes in cloud-native security architectures and DevSecOps.',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    linkedin: '#',
  },
  {
    name: 'Sarah Mitchell',
    title: 'Head of Threat Intelligence',
    bio: 'Former threat analyst for a national cybersecurity agency. Runs SkyTrust\'s global threat intelligence network, processing 800M+ events daily to identify emerging attack patterns.',
    image: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    linkedin: '#',
  },
  {
    name: 'Dr. Angela Reeves',
    title: 'Healthcare Security Lead',
    bio: 'MD-turned-security professional with unique expertise in clinical workflow security. Has led HIPAA compliance programs for 30+ hospital systems and health networks.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
    linkedin: '#',
  },
];

// --- Services ---
export const services = [
  // ── Software & Engineering Services ──
  {
    slug: 'software-development',
    name: 'Custom Software Development',
    icon: 'Code',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    tagline: 'Tailored applications built for scale and speed',
    description: 'End-to-end custom software engineering. From scalable web applications to robust backend systems, we build solutions that drive your business forward.',
    problemNarrative: 'Outgrown off-the-shelf software or legacy monoliths creating operational bottlenecks? Custom software engineering builds tailored, scalable applications directly aligned with your core business processes.',
    methodology: [
      { title: 'Scoping & Architecture', desc: 'Deep dive into your domain logic, user workflows, and system constraints to architect a resilient codebase.' },
      { title: 'Agile Sprints & QA', desc: 'Iterative full-stack development with continuous automated unit, integration, and performance testing.' },
      { title: 'Production Launch & Scaling', desc: 'Zero-downtime release pipelines, real-time SLA monitoring, and ongoing feature enhancement.' },
    ],
    features: [
      'Full-stack web application development',
      'Mobile app development (iOS & Android)',
      'Enterprise architecture & API design',
      'Legacy system modernization',
      'UI/UX design & prototyping',
      'Agile software delivery',
      'Quality Assurance & automated testing',
      'DevOps & CI/CD pipeline integration',
    ],
  },
  {
    slug: 'system-management',
    name: 'System Management',
    icon: 'Server',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    tagline: 'Reliable infrastructure, managed 24/7',
    description: 'Comprehensive IT systems administration and infrastructure management. We ensure your servers, databases, and networks operate at peak performance.',
    problemNarrative: 'System outages, unpatched server vulnerabilities, and internal IT teams spending all day firefighting? Managed system administration eliminates infrastructure overhead while guaranteeing 99.9% uptime.',
    methodology: [
      { title: 'Telemetry & Patch Audit', desc: 'Audit server configurations, patch levels, and deploy lightweight telemetry agents across all nodes.' },
      { title: 'Automation & CIS Hardening', desc: 'Automate routine backups, apply CIS security hardening benchmarks, and streamline OS updates.' },
      { title: '24/7 Managed Operations', desc: 'Round-the-clock proactive monitoring, instant incident triage, and resource capacity planning.' },
    ],
    features: [
      '24/7/365 infrastructure monitoring',
      'Server & database administration',
      'Performance tuning & capacity planning',
      'Automated backup & disaster recovery',
      'Patch management & updates',
      'Network configuration & optimization',
      'Help desk & IT support escalation',
      'Cloud cost optimization',
    ],
  },
  {
    slug: 'cloud-architecture',
    name: 'Cloud Architecture & Dev',
    icon: 'Cloud',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    tagline: 'Build and scale in the modern cloud',
    description: 'Cloud-native development and migration services across AWS, Azure, and GCP. We design resilient architectures that scale on demand.',
    problemNarrative: 'Skyrocketing cloud costs, fragile monolithic architectures, and vendor lock-in slowing release cycles? Cloud-native architecture unlocks elasticity, high availability, and cost governance.',
    methodology: [
      { title: 'Cloud Posture & Cost Assessment', desc: 'Evaluate existing cloud infrastructure, resource utilization, and technical debt across AWS/Azure/GCP.' },
      { title: 'Cloud-Native Re-Architecture', desc: 'Migrate workloads to microservices, containerization (K8s), and Infrastructure as Code (Terraform).' },
      { title: 'Resiliency & Cost Governance', desc: 'Enforce multi-region failover, auto-scaling, and automated cloud cost optimization guardrails.' },
    ],
    features: [
      'Cloud migration strategy & execution',
      'Microservices & containerization (Docker/K8s)',
      'Serverless application development',
      'Multi-cloud & hybrid architecture',
      'Infrastructure as Code (Terraform/Ansible)',
      'High-availability system design',
      'Cloud security & IAM auditing',
      'Data lake & warehouse deployment',
    ],
  },
  {
    slug: 'data-analytics',
    name: 'Data Analytics & BI',
    icon: 'Activity',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    tagline: 'Turn raw data into strategic advantage',
    description: 'End-to-end data engineering, business intelligence, and analytics platforms that give your team actionable insights in real time.',
    problemNarrative: 'Data trapped in isolated databases and SaaS tools, forcing decision-makers to wait weeks for static reports? Integrated data platforms transform raw data into real-time interactive intelligence.',
    methodology: [
      { title: 'Ingestion & Warehouse Design', desc: 'Build automated ETL pipelines into centralized cloud data warehouses (BigQuery/Snowflake).' },
      { title: 'Data Modeling & Governance', desc: 'Clean, transform (dbt), and secure data assets with automated data quality frameworks.' },
      { title: 'Executive BI & Predictive Models', desc: 'Deploy self-service dashboards and predictive analytics models for real-time executive decision-making.' },
    ],
    features: [
      'Data warehouse design & implementation',
      'ETL/ELT pipeline engineering',
      'Real-time streaming analytics',
      'Business intelligence dashboards (Power BI, Tableau)',
      'Machine learning model deployment',
      'Data governance & quality frameworks',
      'Predictive analytics & forecasting',
      'Self-service analytics enablement',
    ],
  },
  {
    slug: 'devops-automation',
    name: 'DevOps & Automation',
    icon: 'Zap',
    image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?auto=format&fit=crop&w=800&q=80',
    tagline: 'Ship faster with confidence',
    description: 'Streamline your software delivery lifecycle with robust CI/CD pipelines, infrastructure automation, and site reliability engineering practices.',
    problemNarrative: 'Manual deployment steps, environment drift, and friction between development and operations teams slowing release velocity? CI/CD and DevOps automation make deployments predictable and zero-touch.',
    methodology: [
      { title: 'Pipeline & Workflow Audit', desc: 'Identify release bottlenecks, deployment friction, and environment configuration drifts.' },
      { title: 'GitOps & IaC Standardization', desc: 'Automate builds, testing, and infrastructure provisioning using Terraform, Docker, and GitOps.' },
      { title: 'Observability & SRE', desc: 'Implement error budgets, automated rollback triggers, and full-stack telemetry monitoring.' },
    ],
    features: [
      'CI/CD pipeline design & implementation',
      'Infrastructure as Code (IaC)',
      'Kubernetes orchestration & Helm charts',
      'GitOps workflows',
      'Automated testing frameworks',
      'Site Reliability Engineering (SRE)',
      'Monitoring, alerting & observability stacks',
      'On-call runbook & incident automation',
    ],
  },
  {
    slug: 'api-integration',
    name: 'API & Systems Integration',
    icon: 'Shield',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    tagline: 'Connect your ecosystem seamlessly',
    description: 'Enterprise API strategy, design, and third-party integration services that unify your technology stack and eliminate data silos.',
    problemNarrative: 'Disconnected enterprise software causing manual data re-entry, brittle webhooks, and failing API rate limits? Clean API architecture unifies your tech stack seamlessly.',
    methodology: [
      { title: 'Contract Design & Routing Specs', desc: 'Map data flows, schema contracts, and API gateway routing rules across systems.' },
      { title: 'Middleware & Security', desc: 'Build secure REST/GraphQL middleware with OAuth2, rate limiting, and message queues.' },
      { title: 'Load Testing & SLA Monitoring', desc: 'Stress test under peak concurrency and establish real-time error logging SLAs.' },
    ],
    features: [
      'RESTful & GraphQL API design',
      'Third-party SaaS integrations (Salesforce, SAP, etc.)',
      'Event-driven architecture & message queues',
      'API gateway setup & management',
      'iPaaS & middleware solutions',
      'Legacy system API wrapping',
      'Webhook & real-time sync engineering',
      'API security & rate limiting',
    ],
  },
  // ── Security Services (matching navbar slugs) ──
  {
    slug: 'network-security',
    name: 'Network Security',
    icon: 'Shield',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
    tagline: 'Defend every layer of your network',
    description: 'Enterprise-grade network perimeter defense, zero-trust segmentation, and continuous threat detection to stop intrusions before they cause damage.',
    problemNarrative: 'Traditional network boundaries are eroding, exposing internal infrastructure to unauthorized lateral movement and unmonitored ingress threats. Zero-trust network security stops intrusions before damage occurs.',
    methodology: [
      { title: 'Deep Inspection & Ingress Mapping', desc: 'Audit perimeter firewalls, active connections, and ingress/egress network boundaries.' },
      { title: 'Zero Trust & Micro-Segmentation', desc: 'Enforce strict network segmentation, SASE/VPN policies, and strict access controls.' },
      { title: 'Automated IPS & Threat Prevention', desc: 'Deploy next-gen IPS, continuous anomaly detection, and automated threat blocking.' },
    ],
    features: [
      'Next-gen firewall (NGFW) deployment & management',
      'Intrusion Detection & Prevention (IDS/IPS)',
      'DDoS mitigation & traffic scrubbing',
      'Network segmentation & micro-segmentation',
      'VPN & SASE architecture',
      'DNS security & web filtering',
      'Network traffic analysis & anomaly detection',
      'SD-WAN security overlay',
    ],
  },
  {
    slug: 'cloud-security',
    name: 'Cloud Security',
    icon: 'Cloud',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    tagline: 'Secure your cloud, wherever it lives',
    description: 'Multi-cloud security posture management, container security, and identity-first protection across AWS, Azure, and GCP environments.',
    problemNarrative: 'Public cloud buckets exposed, privilege creep across IAM roles, and multi-cloud environments operating without central visibility. Cloud security posture management restores total control.',
    methodology: [
      { title: 'Multi-Cloud IAM & CSPM Audit', desc: 'Scan AWS, Azure, and GCP for privilege escalation risks and open storage buckets.' },
      { title: 'Workload & Container Hardening', desc: 'Secure Kubernetes clusters, container registries, and serverless execution environments.' },
      { title: 'Continuous Guardrails & Policy', desc: 'Enforce automated policy guardrails to terminate non-compliant cloud resources instantly.' },
    ],
    features: [
      'Cloud Security Posture Management (CSPM)',
      'Container & Kubernetes security (CKS)',
      'Cloud workload protection (CWPP)',
      'IAM & privileged access management',
      'Serverless & API security',
      'Cloud-native SIEM & SOAR integration',
      'Data loss prevention (DLP)',
      'Continuous compliance monitoring',
    ],
  },
  {
    slug: 'compliance-consulting',
    name: 'Compliance Consulting',
    icon: 'FileCheck',
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=80',
    tagline: 'Audit-ready from day one',
    description: 'Expert guidance through SOC 2, ISO 27001, HIPAA, GDPR, and PCI-DSS compliance programs, from gap assessment to certification.',
    problemNarrative: 'Stalled enterprise sales deals and audit fatigue caused by missing SOC 2 Type II, ISO 27001, HIPAA, or PCI-DSS certifications? Compliance engineering guides you to certification without audit friction.',
    methodology: [
      { title: 'Gap Analysis & Scope Definition', desc: 'Evaluate existing controls against target frameworks (SOC 2, ISO 27001, HIPAA).' },
      { title: 'Policy Library & Evidence Automation', desc: 'Write required policies, configure technical controls, and automate evidence gathering.' },
      { title: 'Audit Escort & Guaranteed Pass', desc: 'Guide your team through external auditor inquiries with a 100% audit pass track record.' },
    ],
    features: [
      'SOC 2 Type I & II readiness & audit support',
      'ISO 27001 implementation & certification',
      'HIPAA Security Rule compliance programs',
      'GDPR data mapping & privacy frameworks',
      'PCI-DSS scoping & QSA coordination',
      'Policy & procedure library creation',
      'Continuous compliance monitoring',
      'Vendor risk management programs',
    ],
  },
  {
    slug: 'threat-monitoring',
    name: 'Threat Monitoring',
    icon: 'Activity',
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
    tagline: '24/7 eyes on your environment',
    description: 'Round-the-clock Security Operations Center (SOC) monitoring powered by advanced SIEM, behavioral analytics, and our global threat intelligence feed.',
    problemNarrative: 'Alert fatigue, unmonitored endpoint activity, and threat actors lurking undetected inside corporate networks for months. 24/7 Managed SOC monitoring provides immediate threat detection.',
    methodology: [
      { title: 'SIEM & Log Ingestion', desc: 'Connect endpoints, cloud audit logs, and firewalls into our 24/7 SIEM correlation engine.' },
      { title: 'Behavioral AI & Threat Hunting', desc: 'Combine machine learning correlation with human threat hunters to expose zero-days.' },
      { title: 'Incident Containment (<15 Min)', desc: 'Isolate compromised hosts immediately, revoke sessions, and issue forensic triage reports.' },
    ],
    features: [
      '24/7/365 SOC-as-a-Service',
      'SIEM deployment & management',
      'Endpoint Detection & Response (EDR)',
      'User & Entity Behavior Analytics (UEBA)',
      'Threat intelligence feed integration',
      'Security alert triage & escalation',
      'Mean time to detect (MTTD) SLA guarantees',
      'Monthly executive threat reports',
    ],
  },
  {
    slug: 'penetration-testing',
    name: 'Penetration Testing',
    icon: 'Target',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    tagline: 'Attack before the attackers do',
    description: 'Certified ethical hackers simulating real-world attacks, from external red team operations to internal adversary simulations and web application testing.',
    problemNarrative: 'Hidden software vulnerabilities, misconfigured cloud ports, and unpatched web applications waiting to be exploited by malicious actors. Ethical red team penetration testing uncovers bugs first.',
    methodology: [
      { title: 'Reconnaissance & OSINT', desc: 'Map external attack surfaces, exposed employee credentials, and perimeter assets.' },
      { title: 'Manual Exploitation (Red Team)', desc: 'Ethical hackers bypass defenses, escalate privileges, and simulate real-world attacks.' },
      { title: 'Remediation & Free Re-Test', desc: 'Provide step-by-step fix guides and re-test remediated flaws at no extra charge.' },
    ],
    features: [
      'External & internal network penetration testing',
      'Web application & API penetration testing',
      'Mobile application security testing',
      'Red team & adversary simulation',
      'Social engineering & phishing campaigns',
      'Physical security assessments',
      'Cloud configuration review',
      'Detailed remediation reporting',
    ],
  },
  {
    slug: 'incident-response',
    name: 'Incident Response',
    icon: 'Zap',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
    tagline: '24/7 breach hotline & rapid containment',
    description: 'When a breach occurs, every minute counts. Our IR team mobilizes instantly, contains the threat, preserves forensic evidence, and restores operations fast.',
    problemNarrative: 'Active ransomware infection, domain controller compromise, or unauthorized database exfiltration in progress. Emergency Incident Response mobilizes in under 15 minutes to contain the threat.',
    methodology: [
      { title: 'Emergency Triage (<15 Min)', desc: 'Immediate hotline response, adversary isolation, and memory/forensic image capture.' },
      { title: 'Threat Eviction & Forensics', desc: 'Eradicate malware persistence, trace attacker lateral movement, and secure credentials.' },
      { title: 'Recovery & Post-Breach Hardening', desc: 'Restore business systems safely, issue regulatory forensic reports, and harden defenses.' },
    ],
    features: [
      '24/7 breach hotline & emergency mobilization',
      'Threat containment & eradication',
      'Digital forensics & evidence preservation',
      'Ransomware negotiation & decryption support',
      'Business continuity coordination',
      'Regulatory notification guidance',
      'Post-incident root cause analysis',
      'IR retainer programs for priority response',
    ],
  },
  {
    slug: 'cybersecurity-services',
    name: 'Cybersecurity & Compliance',
    icon: 'Shield',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
    tagline: 'Secure your code and infrastructure',
    description: 'Enterprise-grade security woven into every line of code. We provide penetration testing, SOC monitoring, and compliance readiness.',
    features: [
      'Application penetration testing',
      'SOC 2 & ISO 27001 readiness',
      'Threat monitoring & incident response',
      'Network security & firewall management',
      'Zero Trust architecture implementation',
      'Code security auditing',
    ],
  },
];

// --- Jobs ---
export const openRoles = [
  { title: 'Senior SOC Analyst', department: 'SOC/Analysts', location: 'Remote / Austin, TX', type: 'Full-time' },
  { title: 'Cloud Security Engineer', department: 'Engineering', location: 'Remote', type: 'Full-time' },
  { title: 'Penetration Tester (Mid/Senior)', department: 'SOC/Analysts', location: 'Remote / New York, NY', type: 'Full-time' },
  { title: 'Compliance Consultant', department: 'Compliance', location: 'Remote', type: 'Full-time' },
  { title: 'Enterprise Account Executive', department: 'Sales', location: 'Chicago, IL', type: 'Full-time' },
  { title: 'Security Sales Engineer', department: 'Sales', location: 'Remote', type: 'Full-time' },
  { title: 'DevSecOps Engineer', department: 'Engineering', location: 'Remote', type: 'Full-time' },
  { title: 'Threat Intelligence Analyst', department: 'SOC/Analysts', location: 'Remote', type: 'Full-time' },
];

// --- Testimonials ---
export const testimonials = [
  {
    quote: "SkyTrust's 24/7 SOC threat monitoring contained a ransomware staging attempt in under 20 minutes without disrupting active production servers.",
    author: "Sarah Johnson",
    company: "VP of IT Infrastructure, TechCorp Solutions",
    stars: 5,
  },
  {
    quote: "Their compliance consulting guided us through SOC 2 Type II and ISO 27001 readiness flawlessly. We passed our audit on the first attempt with zero exceptions.",
    author: "Michael Chen",
    company: "Chief Information Security Officer, Global Finance Inc",
    stars: 5,
  },
  {
    quote: "SkyTrust's cloud architecture and DevOps engineering modernized our multi-cloud stack while maintaining 100% HIPAA compliance across all patient endpoints.",
    author: "Emily Rodriguez",
    company: "Director of Digital Health, HealthFirst Medical",
    stars: 5,
  },
];

// --- FAQ ---
export const faqData = {
  general: [
    { q: "What makes SkyTrust different from other cybersecurity providers?", a: "SkyTrust combines enterprise-grade security expertise with transparent, jargon-free communication. We're proactive rather than reactive: our threat monitoring stops incidents before they become breaches. Every client gets a dedicated analyst, not a ticket queue." },
    { q: "Do you work with small businesses or only enterprises?", a: "We work with organizations of all sizes. Our Starter plan is specifically designed for small businesses that need enterprise-quality security without an enterprise-size budget or internal security team." },
    { q: "How quickly can you onboard a new client?", a: "Most clients are fully onboarded and monitoring within 5-7 business days for threat monitoring. Compliance engagements typically begin with a discovery call and gap assessment within the first week." },
    { q: "Are your analysts US-based?", a: "Our primary SOC operates from the United States with analysts in Austin, TX and New York, NY. We also maintain 24/7 coverage with international team members to ensure round-the-clock operations." },
  ],
  pricing: [
    { q: "Do you offer month-to-month contracts?", a: "Yes. All plans are available month-to-month. We also offer 12-month and 24-month agreements with 10-15% discounts. Enterprise plans are typically custom-scoped annual agreements." },
    { q: "What's included in the free security assessment?", a: "Our complimentary assessment includes a high-level review of your current security controls, identification of obvious gaps, a preliminary risk rating, and a tailored roadmap of recommended services. It takes approximately 90 minutes." },
    { q: "Can I upgrade or downgrade my plan?", a: "Absolutely. You can upgrade at any time effective immediately. Downgrades take effect at the next billing cycle. Enterprise clients can adjust scope with 30 days notice." },
    { q: "Do you offer nonprofit or education pricing?", a: "Yes, we offer 20% discounts for verified nonprofit organizations and educational institutions. Contact our sales team with your 501(c)(3) documentation or .edu domain to apply." },
  ],
  technical: [
    { q: "What SIEM platforms do you integrate with?", a: "We integrate natively with Splunk, Microsoft Sentinel, IBM QRadar, Elastic SIEM, Sumo Logic, and Datadog Security. We can also work with other platforms via our custom connector framework." },
    { q: "Do you require installing agents on our systems?", a: "For threat monitoring, lightweight agents are deployed on endpoints (typically 2-5MB). Network monitoring uses agentless flow analysis. We also integrate with your existing EDR tools (CrowdStrike, SentinelOne, Microsoft Defender)." },
    { q: "How do you handle false positives?", a: "Our analysts manually review all high-severity alerts before escalation. We continuously tune detection rules based on your environment. Most clients see false positive rates below 3% within 60 days of onboarding." },
    { q: "What's your SLA for incident response?", a: "Business plan: 30-minute acknowledgment, 2-hour containment start. Enterprise: 15-minute acknowledgment, 1-hour containment start with dedicated on-call engineer. Starter: 60-minute acknowledgment, 4-hour containment start." },
  ],
  compliance: [
    { q: "Which compliance frameworks do you support?", a: "We support SOC 2 Type I & II, ISO 27001, HIPAA Security & Privacy Rules, GDPR, PCI-DSS Levels 1-4, NIST CSF, CMMC, FedRAMP (advisory), and CCPA. We continuously expand our framework coverage." },
    { q: "Do you help with the actual audit, or just prep?", a: "Both. We prepare you for audit, and we coordinate directly with your chosen audit firm (or can recommend accredited partners). Many clients choose us as their ongoing compliance monitoring partner post-certification." },
    { q: "How long does SOC 2 Type II certification take?", a: "The observation period for SOC 2 Type II is a minimum of 6 months. Total time from kick-off to certification is typically 8-12 months depending on your current control maturity." },
    { q: "Can you help with GDPR compliance if we're a US-based company?", a: "Yes. If you process personal data of EU residents, GDPR applies regardless of where you're based. We help with data mapping, DPA preparation, breach notification procedures, and cross-border transfer mechanisms." },
  ],
};

// --- Solutions ---
export const solutions = [
  {
    slug: 'small-business',
    name: 'Small Business',
    icon: 'Building',
    tagline: 'Enterprise security, scaled for your business',
    description: 'Protect your business from the same threats targeting Fortune 500s, with a platform designed for lean IT teams and strict budgets.',
    features: ['Endpoint Protection', 'Email Security', 'Vulnerability Scanning'],
  },
  {
    slug: 'enterprise',
    name: 'Enterprise',
    icon: 'Building2',
    tagline: 'Comprehensive security for complex environments',
    description: 'Advanced threat detection, incident response, and continuous compliance for large-scale, multi-cloud enterprise architectures.',
    features: ['24/7 SOC-as-a-Service', 'Zero Trust Architecture', 'Cloud Security Posture Management'],
  },
  {
    slug: 'healthcare',
    name: 'Healthcare',
    icon: 'HeartPulse',
    tagline: 'Secure patient data, ensure HIPAA compliance',
    description: 'Protect PHI, secure clinical workflows, and maintain continuous compliance with evolving healthcare regulations.',
    features: ['HIPAA Readiness', 'Medical Device Security', 'Ransomware Defense'],
  },
  {
    slug: 'finance',
    name: 'Finance',
    icon: 'Landmark',
    tagline: 'Bank-grade security and regulatory compliance',
    description: 'Secure financial transactions, protect PII, and streamline compliance audits for PCI-DSS, GLBA, and SEC regulations.',
    features: ['PCI-DSS Compliance', 'Fraud Detection', 'Network Segmentation'],
  },
  {
    slug: 'government',
    name: 'Government',
    icon: 'Landmark',
    tagline: 'Defend public sector infrastructure',
    description: 'Meet stringent government cybersecurity mandates and protect critical infrastructure against nation-state adversaries.',
    features: ['NIST/CMMC Compliance', 'Critical Infrastructure Protection', 'Advanced Threat Hunting'],
  },
];
